version: '3.8'

services:
  my-jenkins:
    image: my-jenkins
    container_name: my-jenkins
    restart: on-failure
    user: "0"  # run as root (dev only; not for production)
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    ports:
      - "9000:8080"
      - "50000:50000"

volumes:
  jenkins-data: