pipeline {
    agent any
    
    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'golang:1.21'
                    //image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}