pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
                    sh '''
                      docker pull golang:1.21
                      docker run --rm -v "$PWD":/go/src/app -w /go/src/app golang:1.21 sh -c "go test -v ./..."
                    '''
                }
            }
        }
    }
}