pipeline {
    agent {
        label 'main'
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'echo "Hello Jenkins!"'
                sh 'date'
            }
        }
    }
}